---
title: "Data tidy"
output: github_document
---

```{r}
library(tidyverse)
```


##Tidy data
```{r}
pulse_data = 
haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
janitor::clean_names()
```

Wide format to long format

```{r}
pulse_data_tidy = 
  pulse_data %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  )
```


rewerite combine and extend to add a muutate
```{r}
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi") %>% 
    relocate(id, visit) %>% 
  mutate(visit = recode(visit, "bl" = "00m"))

```



#Pivot wider

```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )

analysis_result %>% 
  pivot_wider(
    names_from = "time",
    values_from = "mean"
  )
```


#Binding rows using the lord of the rows
```{r}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>% 
  mutate(movie = "lord_ring")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>% 
  mutate(movie = "return_king")
```


Bind all the rows together

```{r}
lotr_tidy = 
  bind_rows(fellowship_ring, two_towers, return_king)
```


```{r}
 relocate(lotr_tidy, movie) %>% 
 janitor::clean_names() %>% 
  pivot_longer(
    female:male,
    names_to = "gender",
    values_to = "words"
  )
```

